In [2]:
import numpy as np

# 1d array
array_1d = np.array([1, 2, 3, 4, 5])
print(type(array_1d))  # Output: <class 'numpy.ndarray'>
print(array_1d)        # Output: [1 2 3 4 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)  # Output: 2
print(array_2d)        # Output: [[1 2 3]
                       #          [4 5 6]]


2
[[1 2 3]
 [4 5 6]]


In [7]:
# 3d array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim)  # Output: 3
print(array_3d)        # Output: [[[1 2]
                       #           [3 4]]
                       #
                       #          [[5 6]
                       #           [7 8]]]
                       
array_3d.shape  # Output: (2, 2, 2)
array_3d.size   # Output: 8
array_3d.dtype  # Output: dtype('int64') or dtype('int32') 
                       

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


dtype('int32')

In [8]:
# upcasting example
array_mixed = np.array([1, 2.5, 3])
print(array_mixed.dtype)  # Output: dtype('float64')
print(array_mixed)        # Output: [1.  2.5 3.]

float64
[1.  2.5 3. ]


In [9]:
# string in numpy 
array_str = np.array(['apple', 'banana', 'cherry'])
print(array_str.dtype)  # Output: dtype('<U6')

<U6
