In [2]:
import numpy as np

# 1d array
array_1d = np.array([1, 2, 3, 4, 5])
print(type(array_1d))  # Output: <class 'numpy.ndarray'>
print(array_1d)        # Output: [1 2 3 4 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)  # Output: 2
print(array_2d)        # Output: [[1 2 3]
                       #          [4 5 6]]


2
[[1 2 3]
 [4 5 6]]


In [4]:
# 3d array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim)  # Output: 3
print(array_3d)        # Output: [[[1 2]
                       #           [3 4]]
                       #
                       #          [[5 6]
                       #           [7 8]]]
                       
array_3d.shape  # Output: (2, 2, 2)
array_3d.size   # Output: 8
array_3d.dtype  # Output: dtype('int64') or dtype('int32') 
                       

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


dtype('int32')

In [5]:
# upcasting example
array_mixed = np.array([1, 2.5, 3])
print(array_mixed.dtype)  # Output: dtype('float64')
print(array_mixed)        # Output: [1.  2.5 3.]

float64
[1.  2.5 3. ]


In [6]:
# string in numpy 
array_str = np.array(['apple', 'banana', 'cherry'])
print(array_str.dtype)  # Output: dtype('<U6')

<U6


In [7]:
# list 
list_data = [10, 20, 30, 40, 50]
array_from_list = np.array(list_data)
print(array_from_list)  # Output: [10 20 30 40 50

[10 20 30 40 50]


In [8]:
# tuple
tuple_data = (100, 200, 300)
array_from_tuple = np.array(tuple_data)
print(array_from_tuple)  # Output: [100 200 300]


[100 200 300]


In [9]:
# set 
set_data = {7, 8, 9}
array_from_set = np.array(set_data)
print(array_from_set)  # Output: [7 8 9] (order may vary)


{8, 9, 7}


In [10]:
# dictionary
dict_data = {'a': 1, 'b': 2, 'c': 3}
array_from_dict = np.array(list(dict_data.values()))
print(array_from_dict)  # Output: [1 2 3]

[1 2 3]


In [13]:

array_zeros = np.zeros((2, 3))
print(array_zeros)  # Output: [[0. 0. 0.]

array_ones = np.ones((3, 2))
print(array_ones)   # Output: [[1. 1.]

array_full = np.full((2, 2), 7)
print(array_full)   

array_random = np.random.rand(2, 3)
print(array_random)  # Output: Random values between 0 and 1

array_uniform = np.random.uniform(5, 10, (2, 2))
print(array_uniform)  # Output: Random values between 5 and 10

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.30147017 0.62990083 0.47127526]
 [0.98284035 0.13567289 0.76340043]]
[[9.15413568 5.45852475]
 [8.25045901 7.76931639]]


In [18]:
array_linspace = np.linspace(1, 10, 10) # start, stop, num
print(array_linspace)  # Output: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

array_logspace = np.logspace(1, 3, 3,base =2) # start, stop, num
print(array_logspace)  # Output: [  2.  4.  8.]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 4. 8.]
