In [1]:
import numpy as np

# 1d array
array_1d = np.array([1, 2, 3, 4, 5])
print(type(array_1d))  # Output: <class 'numpy.ndarray'>
print(array_1d)        # Output: [1 2 3 4 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)  # Output: 2
print(array_2d)        # Output: [[1 2 3]
                       #          [4 5 6]]


2
[[1 2 3]
 [4 5 6]]
