In [24]:
import numpy as np

# 1d array
array_1d = np.array([1, 2, 3, 4, 5])
print(type(array_1d))  # Output: <class 'numpy.ndarray'>
print(array_1d)        # Output: [1 2 3 4 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [25]:
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)  # Output: 2
print(array_2d)        # Output: [[1 2 3]
                       #          [4 5 6]]


2
[[1 2 3]
 [4 5 6]]


In [26]:
# 3d array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.ndim)  # Output: 3
print(array_3d)        # Output: [[[1 2]
                       #           [3 4]]
                       #
                       #          [[5 6]
                       #           [7 8]]]
                       
array_3d.shape  # Output: (2, 2, 2)
array_3d.size   # Output: 8
array_3d.dtype  # Output: dtype('int64') or dtype('int32') 
                       

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


dtype('int32')

In [27]:
# upcasting example
array_mixed = np.array([1, 2.5, 3])
print(array_mixed.dtype)  # Output: dtype('float64')
print(array_mixed)        # Output: [1.  2.5 3.]

float64
[1.  2.5 3. ]


In [28]:
# string in numpy 
array_str = np.array(['apple', 'banana', 'cherry'])
print(array_str.dtype)  # Output: dtype('<U6')

<U6


In [29]:
# list 
list_data = [10, 20, 30, 40, 50]
array_from_list = np.array(list_data)
print(array_from_list)  # Output: [10 20 30 40 50

[10 20 30 40 50]


In [30]:
# tuple
tuple_data = (100, 200, 300)
array_from_tuple = np.array(tuple_data)
print(array_from_tuple)  # Output: [100 200 300]


[100 200 300]


In [31]:
# set 
set_data = {7, 8, 9}
array_from_set = np.array(set_data)
print(array_from_set)  # Output: [7 8 9] (order may vary)


{8, 9, 7}


In [32]:
# dictionary
dict_data = {'a': 1, 'b': 2, 'c': 3}
array_from_dict = np.array(list(dict_data.values()))
print(array_from_dict)  # Output: [1 2 3]

[1 2 3]


In [33]:

array_zeros = np.zeros((2, 3))
print(array_zeros)  # Output: [[0. 0. 0.]

array_ones = np.ones((3, 2))
print(array_ones)   # Output: [[1. 1.]

array_full = np.full((2, 2), 7)
print(array_full)   

array_random = np.random.rand(2, 3)
print(array_random)  # Output: Random values between 0 and 1

array_uniform = np.random.uniform(5, 10, (2, 2))
print(array_uniform)  # Output: Random values between 5 and 10

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.27130403 0.60209236 0.26183937]
 [0.10486468 0.34522078 0.47584808]]
[[9.08040832 8.5970764 ]
 [5.96162361 7.22811667]]


In [34]:
array_linspace = np.linspace(1, 10, 10) # start, stop, num
print(array_linspace)  # Output: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

array_logspace = np.logspace(1, 3, 3,base =2) # start, stop, num
print(array_logspace)  # Output: [  2.  4.  8.]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 4. 8.]


In [35]:
# matrix
# primary diagonal
matrix_diag = np.diag([1, 2, 3])
print(matrix_diag)  # Output: [[1 0 0]

matrix_diag_k1 = np.diag([1, 2, 3], k=1)
print(matrix_diag_k1)  # Output: [[0 1 0 0]
                       #          [0 0 2 0]
                       #          [0 0 0 3]
                       #          [0 0 0 0]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [36]:
matrix_eye = np.eye(3)
print(matrix_eye)  # Output: [[1. 0. 0.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# indexing and slicing

array_index = np.array([10, 20, 30, 40, 50])
print(array_index[2])    # Output: 30

# ndarray slicing
array_slice = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15]])
print(array_slice[1:, 2:4])  # Output: [[ 8  9]  from row 1 to end, column 2 to 3
                             #          [13 14]]


30
[[ 8  9]
 [13 14]]


In [ ]:
# Advanced Indexing and Slicing
array_adv = np.array([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])
print(array_adv[[0, 2], [1, 2]])  # Output: [20 90] from (0,1) and (2,2)

# Boolean Indexing
array_bool = np.array([5, 10, 15, 20, 25])
mask = array_bool > 15
print(array_bool[mask])  # Output: [20 25]

[20 90]
[20 25]


In [47]:
a = np.array([1,2,3,4,5])
a[1:4] = 0
print(a)  # Output: [1 0 0 0 5]

[1 0 0 0 5]
