In [16]:
import numpy as np 

arr = np.random.randint(1,100, size=(10,5)) # sample = 10 rows and features = 5
print(arr)

[[45 41 26 69 16]
 [13 20 21 95 12]
 [ 8 85 52 31 60]
 [77  6  1  5 36]
 [29 36 47  4 46]
 [32 83 78 12 62]
 [57 39 45  9 74]
 [38 53 59 42 52]
 [78 38 49 38 74]
 [82 89 21 54 58]]


In [17]:
reshaped = arr.reshape(5,10)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

[[45 41 26 69 16 13 20 21 95 12]
 [ 8 85 52 31 60 77  6  1  5 36]
 [29 36 47  4 46 32 83 78 12 62]
 [57 39 45  9 74 38 53 59 42 52]
 [78 38 49 38 74 82 89 21 54 58]]
[45 41 26 69 16 13 20 21 95 12  8 85 52 31 60 77  6  1  5 36 29 36 47  4
 46 32 83 78 12 62 57 39 45  9 74 38 53 59 42 52 78 38 49 38 74 82 89 21
 54 58]


In [18]:
ravelled = reshaped.ravel(order='F')  # order='C' for row-major, order='F' for column-major
print(ravelled)

[45  8 29 57 78 41 85 36 39 38 26 52 47 45 49 69 31  4  9 38 16 60 46 74
 74 13 77 32 38 82 20  6 83 53 89 21  1 78 59 21 95  5 12 42 54 12 36 62
 52 58]


In [21]:
a = np.random.randint(1,10,size=(3,4))
b = np.random.randint(1,10,size=(3,4))

print(a)
print(b)

con_row = np.concatenate((a,b), axis=0)  # row-wise
print(con_row)

con_col = np.concatenate((a,b), axis=1)  # column-wise
print(con_col)

[[7 1 1 8]
 [2 8 3 4]
 [2 3 8 4]]
[[1 9 1 3]
 [1 2 2 9]
 [9 4 3 8]]
[[7 1 1 8]
 [2 8 3 4]
 [2 3 8 4]
 [1 9 1 3]
 [1 2 2 9]
 [9 4 3 8]]
[[7 1 1 8 1 9 1 3]
 [2 8 3 4 1 2 2 9]
 [2 3 8 4 9 4 3 8]]
