# version 1

In [34]:
import torch
import torch.nn as nn

In [35]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear(features)
#     out = self.sigmoid(out)

#     return out

# Version 2

In [36]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

In [37]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [38]:
# Create dataset

features = torch.rand(10,5)

In [39]:
features

tensor([[0.3093, 0.3728, 0.0604, 0.5542, 0.5136],
        [0.9912, 0.7313, 0.1563, 0.9874, 0.6044],
        [0.0986, 0.3076, 0.3983, 0.2346, 0.1114],
        [0.0549, 0.6741, 0.6605, 0.8429, 0.1643],
        [0.5295, 0.1740, 0.2711, 0.3763, 0.4918],
        [0.2835, 0.8448, 0.4141, 0.5511, 0.5252],
        [0.3823, 0.3411, 0.9211, 0.3679, 0.0540],
        [0.6474, 0.9726, 0.4036, 0.3455, 0.7945],
        [0.9692, 0.8612, 0.7184, 0.6367, 0.5322],
        [0.4901, 0.7219, 0.7347, 0.4137, 0.1061]])

In [40]:
features.shape[1]

5

In [41]:
#create model

model = Model(features.shape[1])

In [42]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.4534],
        [0.4700],
        [0.4800],
        [0.4961],
        [0.4623],
        [0.4757],
        [0.5095],
        [0.4705],
        [0.4981],
        [0.5075]], grad_fn=<SigmoidBackward0>)

In [43]:
#show model weights

model.network[0].weight   # first Linear layer weights
model.network[0].bias

model.network[2].weight   # second Linear layer weights
model.network[2].bias

Parameter containing:
tensor([-0.1901], requires_grad=True)

In [44]:

!pip install torchinfo

  Using cached torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Using cached torchinfo-1.8.0-py3-none-any.whl (23 kB)


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\torchinfo'
Consider using the `--user` option or check the permissions.



In [45]:
from torchinfo import summary

summary( model,input_size = (10,5) )

ModuleNotFoundError: No module named 'torchinfo'

# Extra

In [ ]:
# Base Class
class Rectangle:
    def __init__(self, length, width):
        print("Rectangle constructor called")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width


# Child Class (Square inherits Rectangle)
class Square(Rectangle):
    def __init__(self, side):
        print("Square constructor called")
        super().__init__(side, side)   # Calls Rectangle constructor

    def square_info(self):
        return f"Square area: {self.area()}"


# Child Class (Cube inherits Square)
class Cube(Square):
    def __init__(self, side):
        print("Cube constructor called")
        super().__init__(side)   # Calls Square constructor

    def volume(self):
        return self.length ** 3


# Create Object
cube = Cube(4)

print("Area:", cube.area())
print("Volume:", cube.volume())