# version 1

In [24]:
import torch
import torch.nn as nn

In [25]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear(features)
#     out = self.sigmoid(out)

#     return out

# Version 2

In [26]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

In [27]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [28]:
# Create dataset

features = torch.rand(10,5)

In [29]:
features

tensor([[0.2852, 0.3683, 0.8429, 0.9620, 0.9519],
        [0.0269, 0.9002, 0.7061, 0.5856, 0.9011],
        [0.6790, 0.7245, 0.1015, 0.8526, 0.9400],
        [0.3493, 0.7366, 0.6463, 0.9377, 0.4592],
        [0.2467, 0.1914, 0.3337, 0.3256, 0.2805],
        [0.9666, 0.5444, 0.5084, 0.8650, 0.6482],
        [0.6481, 0.4418, 0.6528, 0.6434, 0.3317],
        [0.8374, 0.5656, 0.8142, 0.1050, 0.6813],
        [0.1223, 0.0707, 0.8217, 0.8714, 0.0979],
        [0.0191, 0.8225, 0.4049, 0.2067, 0.3479]])

In [30]:
features.shape[1]

5

In [31]:
#create model

model = Model(features.shape[1])

In [32]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.3802],
        [0.3774],
        [0.4065],
        [0.3879],
        [0.4085],
        [0.4076],
        [0.4030],
        [0.4059],
        [0.3889],
        [0.3956]], grad_fn=<SigmoidBackward0>)

In [33]:
#show model weights

model.network[0].weight   # first Linear layer weights
model.network[0].bias

model.network[2].weight   # second Linear layer weights
model.network[2].bias

Parameter containing:
tensor([-0.3126], requires_grad=True)

In [34]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Extra

In [35]:
# Base Class
class Rectangle:
    def __init__(self, length, width):
        print("Rectangle constructor called")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width


# Child Class (Square inherits Rectangle)
class Square(Rectangle):
    def __init__(self, side):
        print("Square constructor called")
        super().__init__(side, side)   # Calls Rectangle constructor

    def square_info(self):
        return f"Square area: {self.area()}"


# Child Class (Cube inherits Square)
class Cube(Square):
    def __init__(self, side):
        print("Cube constructor called")
        super().__init__(side)   # Calls Square constructor

    def volume(self):
        return self.length ** 3


# Create Object
cube = Cube(4)

print("Area:", cube.area())
print("Volume:", cube.volume())

Cube constructor called
Square constructor called
Rectangle constructor called
Area: 16
Volume: 64
