In [12]:
import numpy as np 

arr = np.random.randint(1,100, size=(10,5)) # sample = 10 rows and features = 5
print(arr)

[[18  5 77 49 35]
 [35 97  1 33 62]
 [56  7 36 75 54]
 [68 49 18 66 50]
 [97 98 63 20 33]
 [30 21 74 59 74]
 [32 78 37  8 30]
 [ 6 97 12 19 80]
 [36 16 33 38 39]
 [17 67 72 94 74]]


In [13]:
b = arr.reshape(5,10)
print(b)

flattened = b.flatten()
print(flattened)

[[18  5 77 49 35 35 97  1 33 62]
 [56  7 36 75 54 68 49 18 66 50]
 [97 98 63 20 33 30 21 74 59 74]
 [32 78 37  8 30  6 97 12 19 80]
 [36 16 33 38 39 17 67 72 94 74]]
[18  5 77 49 35 35 97  1 33 62 56  7 36 75 54 68 49 18 66 50 97 98 63 20
 33 30 21 74 59 74 32 78 37  8 30  6 97 12 19 80 36 16 33 38 39 17 67 72
 94 74]


In [ ]:
ravelled = b.ravel(order='F')  # order='C' for row-major, order='F' for column-major
print(ravelled)

[18 56 97 32 36  5  7 98 78 16 77 36 63 37 33 49 75 20  8 38 35 54 33 30
 39 35 68 30  6 17 97 49 21 97 67  1 18 74 12 72 33 66 59 19 94 62 50 74
 80 74]
