In [72]:
import torch

data = torch.tensor(
    [
        [2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [73]:
x = data[:,0:2]
y = data[:,2]

print(x)
print(y)

tensor([[2, 3],
        [5, 6],
        [7, 8]])
tensor([3, 4, 5])


In [74]:
# Check CUDA status
import torch
print('Torch:', torch.__version__)
print('Torch CUDA build:', torch.version.cuda)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('Device:', torch.cuda.get_device_name(0))

Torch: 2.11.0+cu128
Torch CUDA build: 12.8
CUDA available: True
Device: NVIDIA GeForce RTX 3060 Laptop GPU


In [75]:
# Move tensor to GPU if available, else keep on CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
data = data.to(device)
x = x.to(device)
y = y.to(device)
print('Using device:', device)
print('data device:', data.device)

Using device: cuda
data device: cuda:0


### Weight Initialization
Weight initialization is a crucial step in training neural networks, as it can significantly impact the convergence and performance of the model. Proper initialization can help prevent issues such as vanishing or exploding gradients, which can hinder the training process.
There are several common methods for weight initialization, including:
1. **Random Initialization**: Weights are initialized randomly, often using a uniform or normal distribution. This method can work but may lead to issues with convergence if not done carefully.
2. **Xavier Initialization**: Also known as Glorot initialization, this method initializes weights based on the number of input and output neurons. It helps maintain the variance of activations across layers, which can improve convergence.
3. **He Initialization**: This method is similar to Xavier initialization but is designed for layers with ReLU activation functions. It initializes weights based on the number of input neurons, which can help prevent vanishing gradients.
4. **Orthogonal Initialization**: Weights are initialized to be orthogonal, which can help maintain the stability of the network during training.
Choosing the right weight initialization method can depend on the architecture of the neural network and the activation functions used. It is often beneficial to experiment with different initialization methods to find the one that works best for a specific problem.

In [76]:
def initialize_parameters():
    parameters = {}
    parameters['w1']= torch.ones((2,2))*0.1
    parameters['b2']= torch.zeros((2,1))
    parameters['w2']= torch.ones((2,1))*0.1
    parameters['b2']= torch.zeros((1,1))
    return parameters

initialize_parameters()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b2': tensor([[0.]]),
 'w2': tensor([[0.1000],
         [0.1000]])}

In [77]:
# & Better way to initialize parameters
def initialize_parameters(layer_dims):
    torch.manual_seed(3)  # For reproducibility
    parameters = {}
    L = len(layer_dims)  # Number of layers in the network
    for l in range(1, L):
        parameters['w' + str(l)] = torch.ones((layer_dims[l - 1], layer_dims[l])) * 0.1
        parameters['b' + str(l)] = torch.zeros((layer_dims[l], 1))

    return parameters    

initialize_parameters([2, 2, 1])

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

In [78]:

#* Forward Propagation
def linear_forward(A_prev, W, b):
    Z = torch.mm(W.T, A_prev) + b
    return Z

In [79]:
def L_layer_forward(X,parameters):
    A = X
    L = len(parameters) // 2  # Number of layers in the network
    for l in range(1,L+1):
        A_prev = A
        W = parameters['w' + str(l)]
        b = parameters['b' + str(l)]
        A = linear_forward(A_prev, W, b)
    return A,A_prev

In [ ]:
params = initialize_parameters([2, 2, 1])
params = {k: v.to(device) for k, v in params.items()}

X_sample = x[0].reshape(2,1).float()
y_hat, A1 = L_layer_forward(X_sample, params)
y_hat
params

tensor([[0.1000]], device='cuda:0')