In [2]:
import torch

data = torch.tensor(
    [
        [2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [4]:
x = data[:,0:2]
y = data[:,2]

print(x)
print(y)

tensor([[2, 3],
        [5, 6],
        [7, 8]])
tensor([3, 4, 5])
