In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
    print("CUDA is available. GPU will be used.")
    print("CUDA version:", torch.version.cuda)
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available. CPU will be used.")    

CUDA is available. GPU will be used.
CUDA version: 12.8
Device name: NVIDIA GeForce RTX 3060 Laptop GPU


In [5]:

x = torch.tensor([1.0, 2.0, 3.0])
print(x)
x.shape

tensor([1., 2., 3.])


torch.Size([3])

In [6]:
torch.empty_like(x)

tensor([9.2196e-41, 0.0000e+00, 0.0000e+00])

In [7]:
torch.zeros_like(x)

tensor([0., 0., 0.])

In [8]:
torch.rand_like(x,dtype=torch.float64)

tensor([0.6607, 0.7280, 0.1085], dtype=torch.float64)

### Data Types in torch
In programming, data types are classifications that specify which type of value a variable can hold. PyTorch supports various data types:

- **Integer (torch.int32)**: Represents 32-bit whole numbers (e.g., `torch.tensor([1, -5, 42], dtype=torch.int32)`).
- **Integer (torch.int64)**: Represents 64-bit whole numbers, default for integer tensors (e.g., `torch.tensor([1, -5, 42], dtype=torch.int64)`).
- **Float (torch.float32)**: Represents 32-bit decimal numbers, default for float tensors (e.g., `torch.tensor([3.14, -0.001], dtype=torch.float32)`).
- **Float (torch.float64)**: Represents 64-bit decimal numbers for higher precision (e.g., `torch.tensor([3.14, -0.001], dtype=torch.float64)`).
- **Boolean (torch.bool)**: Represents true or false values (e.g., `torch.tensor([True, False], dtype=torch.bool)`).
- **Complex (torch.complex64)**: Represents 32-bit complex numbers (e.g., `torch.tensor([1+2j], dtype=torch.complex64)`).
- **Complex (torch.complex128)**: Represents 64-bit complex numbers (e.g., `torch.tensor([1+2j], dtype=torch.complex128)`).
- **Half (torch.float16)**: Represents 16-bit floating-point numbers for memory efficiency (e.g., `torch.tensor([3.14], dtype=torch.float16)`).

You can specify the data type when creating a tensor using the `dtype` parameter, or convert existing tensors using `.to()` method (e.g., `x.to(torch.float32)`).



In [ ]:

#! Mathematical operations
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division

#! Matrix operations
A = torch.tensor([[1.0, 2.0], [3.0,
4.0]])
B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
print(A @ B)  # Matrix multiplication
print(A.T)  # Transpose of A
print(A.inverse())  # Inverse of A (if A is invertible)