In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
    print("CUDA is available. GPU will be used.")
    print("CUDA version:", torch.version.cuda)
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available. CPU will be used.")    

CUDA is available. GPU will be used.
CUDA version: 12.8
Device name: NVIDIA GeForce RTX 3060 Laptop GPU


In [5]:

x = torch.tensor([1.0, 2.0, 3.0])
print(x)
x.shape

tensor([1., 2., 3.])


torch.Size([3])

In [6]:
torch.empty_like(x)

tensor([9.2196e-41, 0.0000e+00, 0.0000e+00])

In [7]:
torch.zeros_like(x)

tensor([0., 0., 0.])

In [ ]:
torch.rand_like(x,dtype=torch.float64)